[package]
name = "gpu"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu.workspace = true
pollster = "0.4.0"
macros.workspace = true
utils.workspace = true
math.workspace = true
logging.workspace = true
