[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[dependencies]
winit.workspace = true
pollster = "0.4.0"
renderer.workspace = true
nalgebra.workspace = true
spin_sleep = "1.3.3"
wgpu.workspace = true
macros-derive.workspace = true
