[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[dependencies]
winit.workspace = true
math.workspace = true
macros.workspace = true
spin_sleep = "1.3.3"
common.workspace = true
wgpu.workspace = true
pollster = "0.4.0"
renderer.workspace = true
traccia.workspace = true
