[package]
name = "renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu.workspace = true
winit.workspace = true
macros.workspace = true
math.workspace = true
traccia.workspace = true
gpu.workspace = true
utils.workspace = true
arc-swap = "1.7.1"
assets.workspace = true
