[package]
name = "renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu.workspace = true
winit.workspace = true
macros.workspace = true
math.workspace = true
traccia.workspace = true
common.workspace = true
image = "0.25.9"
crunch = "0.5.3"
fontdue = "0.9.3"
