[package]
name = "renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu.workspace = true
winit.workspace = true
common.workspace = true
macros.workspace = true
macros-derive.workspace = true
math.workspace = true
gltf = "1.4.1"
