[package]
name = "renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu.workspace = true
winit.workspace = true
math.workspace = true
macros.workspace = true
common.workspace = true
mini-moka = "0.10.3"
traccia.workspace = true
